# Generated by Django 4.2 on 2023-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
