# Generated by Django 4.2 on 2023-04-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0003_modelyear_alter_car_make_alter_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(db_index=True, max_length=350),
        ),
    ]
