# Generated by Django 4.2 on 2023-05-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("car_api", "0004_alter_model_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="trim",
            name="make",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trims",
                to="car_api.make",
            ),
            preserve_default=False,
        ),
    ]
